### ISSUE TITLE
Can't create project with npm init @atomico

### ISSUE THREAD

**Issue by threeid** [atomicojs/atomico#12]
Hello UpperCod,

I can't initialize project with `npm init`
MacOS: 10.14.5
Node: v12.5.0

<img width="576" alt="Screen Shot 2019-07-09 at 9 58 40 PM" src="https://user-images.githubusercontent.com/37827220/60899614-f7eee980-a294-11e9-8577-3aca84f80cdc.png">

Maybe there is a way to create atomico app with something like create-atomico-app with both npm and yarn like create react app or vue init?

I would like to contribute. Do you have any direction for me?

**Comment by threeid** [comment]
Because of function `mkdirpath` in package `template-folder`.

https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback
Why do you implement mkdir recursively while `fs.mkdir` already did that and 
default mode is also 0o777, (you has 0777 in the code)

**Comment by UpperCod** [comment]
Hi! @threeid thanks for your issue, I apologize for the error, now I have generated a maintenance on [template-folder](https://github.com/UpperCod/template-folder) and I generated an update on [@atomico/create](https://github.com/atomicojs/create). 

The problem is that I am not a mac user to check the result of these changes, I hope your confirmation if the process has been successfully completed.

**Comment by threeid** [comment]
It works now. Thanks!
