### ISSUE TITLE
Unexpected token: 'export'

### ISSUE THREAD

**Issue by dy** [atomicojs/atomico#16]
I was trying to illustrate #10 with codesandbox, and seems that atomico breaks there:
https://codesandbox.io/s/fervent-cohen-1lymq?fontsize=14

**Comment by UpperCod** [comment]
Thanks for notifying, the problem happens because of a parcel resolution but only in codesanbox, if you download and install the same image on your computer it will work correctly.

It can be solved by importing from `atomico/src`, but it is still a BUG that I am analyzing.

https://codesandbox.io/s/immutable-field-79hd9

> Atomico uses rollup to optimize the import, this generates 2 chunk, apparently codesanbox does not solve the chunk.... you want atomic you don't need rollup, the code could be distributed without the need to minify **what do you think about this?**

**Comment by UpperCod** [comment]
Solved, check https://codesandbox.io/s/immutable-field-79hd9

**Comment by dy** [comment]
Awesome!
